In [2]:
import pandas as pd

In [4]:
dfLinkedinCanada = pd.read_csv("./Datasets/linkedin_canada.csv")

In [6]:
dfLinkedinCanada.head()

,applicationsCount,companyId,companyName,contractType,description,experienceLevel,location,postedTime,publishedAt,salary,sector,title,workType
0,Over 200 applicants,11000395.0,Embarq,Full-time,About Embarq\n\nWe help VC-backed US startups ...,Mid-Senior level,"Quebec, Canada",2 weeks ago,2024-01-05,NaN,IT Services and IT Consulting and Software Dev...,Machine Learning Engineer,Engineering and Information Technology
1,Over 200 applicants,912833.0,Thumbtack,Full-time,A home is the biggest investment most people m...,Not Applicable,"Ontario, Canada",2 weeks ago,2024-01-05,NaN,"Technology, Information and Internet","Data Scientist, Business Analytics",Engineering and Information Technology
2,Over 200 applicants,10064814.0,Clarifai,Full-time,"About The Company\n\nClarifai is a leading, fu...",Mid-Senior level,"Montreal, Quebec, Canada",4 months ago,2023-09-15,NaN,"Technology, Information and Internet",Data Scientist,Engineering and Information Technology
3,Over 200 applicants,6637598.0,Drop,Full-time,"As a member of the Data Science team, you are ...",Not Applicable,"Toronto, Ontario, Canada",2 months ago,2023-11-15,NaN,"Transportation, Logistics, Supply Chain and St...","Data Science, Investment Research",Engineering and Information Technology
4,Over 200 applicants,2681218.0,Logikk,Full-time,Data Scientist - Computer Vision Tech Company ...,Mid-Senior level,"Montreal, Quebec, Canada",2 weeks ago,2024-01-05,NaN,IT Services and IT Consulting,Data Scientist,Engineering

In [8]:
dfLinkedinCanada.shape

(275, 13)

In [10]:
dfLinkedinCanada.columns

Index(['applicationsCount', 'companyId', 'companyName', 'contractType',
       'description', 'experienceLevel', 'location', 'postedTime',
       'publishedAt', 'salary', 'sector', 'title', 'workType'],
      dtype='object')

In [12]:
df2 = dfLinkedinCanada.drop(['companyId','description','postedTime','publishedAt','salary'], axis = 1)

In [14]:
df2

,applicationsCount,companyName,contractType,experienceLevel,location,sector,title,workType
0,Over 200 applicants,Embarq,Full-time,Mid-Senior level,"Quebec, Canada",IT Services and IT Consulting and Software Dev...,Machine Learning Engineer,Engineering and Information Technology
1,Over 200 applicants,Thumbtack,Full-time,Not Applicable,"Ontario, Canada","Technology, Information and Internet","Data Scientist, Business Analytics",Engineering and Information Technology
2,Over 200 applicants,Clarifai,Full-time,Mid-Senior level,"Montreal, Quebec, Canada","Technology, Information and Internet",Data Scientist,Engineering and Information Technology
3,Over 200 applicants,Drop,Full-time,Not Applicable,"Toronto, Ontario, Canada","Transportation, Logistics, Supply Chain and St...","Data Science, Investment Research",Engineering and Information Technology
4,Over 200 applicants,Logikk,Full-time,Mid-Senior level,"Montreal, Quebec, Canada",IT Services and IT Consulting,Data Scientist,Engineering
...,...,...,...,...,...,...,...,...
270,Over 200 applicants,StackAdapt,Full-time,Entry level,Canada,"Technology, Information and Internet","Software Engineer, Backend (Intermediate/Senior)",Engineering and Information Technology
271,45 applicants,Kinaxis,Full-time,Internship,"Québec, Quebec, Canada",Software Development,"Co-Op/Intern Developer, DevOps",Engineering and Information Technology
272,Over 200 applicants,Saks,Full-time,Associate,Canada,Software Development,Atlassian Systems Engineer,Information Technology
273,57 applicants,Kinaxis,Full-time,Internship,"Waterloo, Ontario, Canada",Software Development,"Co-Op/Intern Developer, DevOps",Engineering and Information Technology
274,Be among the first 25 applicants,NaN,NaN,Contract,"British Columbia, Canada",NaN,Senior React Developer,NaN

In [18]:
sorted_df2 = df2.sort_values(['contractType','experienceLevel']).reset_index(drop=True)
sorted_df2

,applicationsCount,companyName,contractType,experienceLevel,location,sector,title,workType
0,Over 200 applicants,TELUS,Contract,Associate,"Greater Toronto Area, Canada",Software Development and Telecommunications,AI Engineer,Information Technology and Strategy/Planning
1,Over 200 applicants,Zortech Solutions,Contract,Associate,Canada,Human Resources Services,Senior Analytics and Reporting Specialist-Canada,"Research, Analyst, and Information Technology"
2,182 applicants,Software International,Contract,Entry level,"Ontario, Canada",Human Resources,Machine Learning Engineer (remote),Engineering and Information Technology
3,98 applicants,PrecisionERP Incorporated,Contract,Entry level,"Winnipeg, Manitoba, Canada","Software Development, Banking, and Insurance",Automation Developer,"Information Technology, Accounting/Auditing, a..."
4,107 applicants,Software International,Contract,Entry level,"Toronto, Ontario, Canada",Human Resources,Python Developer - REMOTE,Engineering and Information Technology
...,...,...,...,...,...,...,...,...
270,Over 200 applicants,Teal.dev,NaN,Full-time,Canada,NaN,Platform Engineer,NaN
271,Over 200 applicants,Tribble,NaN,Full-time,"Greater Toronto Area, Canada",NaN,Lead Full Stack Developer,NaN
272,Over 200 applicants,dandelion,NaN,Full-time,"Ontario, Canada",NaN,Blockchain Software/Protocol Engineer,NaN
273,Be among the first 25 applicants,Blue Guardian,NaN,Internship,Canada,NaN,Graduate Mental Health Researcher - Mental Hea...,NaN
274,Be among the first 25 applicants,Staffbee Solutions INC,NaN,Part-time,Canada,NaN,GCP Data Engineer (Freelance),NaN

In [21]:
sliced_df2 = sorted_df2.iloc[149:200,1:6]
sliced_df2

,companyName,contractType,experienceLevel,location,sector
149,Mappedin,Full-time,Mid-Senior level,"Ontario, Canada",Internet Publishing
150,Affirm,Full-time,Mid-Senior level,"Victoria, British Columbia, Canada",Financial Services
151,Everbridge,Full-time,Mid-Senior level,"Vancouver, British Columbia, Canada",Software Development
152,"Reddit, Inc.",Full-time,Mid-Senior level,"British Columbia, Canada",Software Development
153,Binary Stream Software - ERP Solutions,Full-time,Mid-Senior level,Canada,Software Development and Financial Services
154,Arctic Wolf,Full-time,Mid-Senior level,"Greater Toronto Area, Canada",Computer and Network Security
155,eStaffing Inc.,Full-time,Mid-Senior level,Canada,Staffing and Recruiting
156,Affirm,Full-time,Mid-Senior level,"Regina, Saskatchewan, Canada",Financial Services
157,Yelp,Full-time,Mid-Senior level,"Toronto, Ontario, Canada","Advertising Services, Software Development, an..."
158,Assent,Full-time,Mid-Senior level,"Ottawa, Ontario, Canada",Software Development
159,Techedin,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
160,GiftCash,Full-time,Mid-Senior level,Canada,"Technology, Information and Internet"
161,Techedin,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
162,Affirm,Full-time,Mid-Senior level,"Winnipeg, Manitoba, Canada",Financial Services
163,Abnormal Security,Full-time,Mid-Senior level,Canada,Computer and Network Security
164,Affirm,Full-time,Mid-Senior level,"Queens, Prince Edward Island, Canada",Financial Services
165,Collective,Full-time,Mid-Senior level,"Vancouver, British Columbia, Canada","Technology, Information and Internet"
166,"Coalition, Inc.",Full-time,Mid-Senior level,"Greater Toronto Area, Canada",Insurance
167,Affirm,Full-time,Mid-Senior level,"London, Ontario, Canada",Financial Services
168,Navigator - Powered By LifeRaft,Full-time,Mid-Senior level,"Halifax, Nova Scotia, Canada","Technology, Information and Internet"
169,Sync.com,Full-time,Mid-Senior level,"Toronto, Ontario, Canada",Internet Publishing
170,TEHORA inc.,Full-time,Mid-Senior level,Canada,"Technology, Information and Internet"
171,White Bay,Full-time,Mid-Senior level,"Vancouver, British Columbia, Canada","Software Development, Computer Games, and IT S..."
172,Quora,Full-time,Mid-Senior level,Canada,"Software Development and Technology, Informati..."
173,GPTZero,Full-time,Mid-Senior level,"Toronto, Ontario, Canada","Technology, Information and Media"
174,Stripe,Full-time,Mid-Senior level,Canada,"Software Development, Technology, Information ..."
175,Lever Middleware Test Company 2,Full-time,Mid-Senior level,"Toronto, Ontario, Canada","Technology, Information and Internet"
176,Affirm,Full-time,Mid-Senior level,"Victoria, British Columbia, Canada",Financial Services
177,Kinaxis,Full-time,Mid-Senior level,"Toronto, Ontario, Canada",Software Development
178,Leonardo.Ai,Full-time,Mid-Senior level,Canada,"Technology, Information and Internet"
179,Techedin,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
180,Lightci (Light Consulting),Full-time,Mid-Senior level,Canada,"IT Services and IT Consulting, Software Develo..."
181,Terminal,Full-time,Mid-Senior level,Canada,Software Development
182,RAZR,Full-time,Mid-Senior level,"Vancouver, British Columbia, Canada",Internet Publishing
183,Luxoft,Full-time,Mid-Senior level,Canada,Software Development
184,HCLTech,Full-time,Mid-Senior level,Canada,Consumer Services
185,Techedin,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
186,Affirm,Full-time,Mid-Senior level,"Hamilton, Ontario, Canada",Financial Services
187,SecurityScorecard,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting and Computer and...
188,Altus Group,Full-time,Mid-Senior level,"Toronto, Ontario, Canada",Leasing Non-residential Real Estate
189,GitLab,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting and Software Dev...
190,Mapbox,Full-time,Mid-Senior level,Canada,Software Development
191,Tucows,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
192,Applied Systems Canada,Full-time,Mid-Senior level,Canada,Software Development
193,Yelp,Full-time,Mid-Senior level,"Vancouver, British Columbia, Canada","Advertising Services, Software Development, an..."
194,Techedin,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting
195,Stripe,Full-time,Mid-Senior level,Canada,"Software Development, Technology, Information ..."
196,Quora,Full-time,Mid-Senior level,Canada,"Software Development and Technology, Informati..."
197,Arctic Wolf,Full-time,Mid-Senior level,Canada,Computer and Network Security
198,Kinaxis,Full-time,Mid-Senior level,"Québec, Quebec, Canada",Software Development
199,Pivotree,Full-time,Mid-Senior level,Canada,IT Services and IT Consulting

In [23]:
print(sliced_df2['companyName'].value_counts())

companyName
Affirm                                    7
Techedin                                  5
Quora                                     2
Kinaxis                                   2
Arctic Wolf                               2
Yelp                                      2
Stripe                                    2
Luxoft                                    1
Leonardo.Ai                               1
Lightci (Light Consulting)                1
Terminal                                  1
RAZR                                      1
SecurityScorecard                         1
HCLTech                                   1
Altus Group                               1
GitLab                                    1
Mapbox                                    1
Tucows                                    1
Applied Systems Canada                    1
Lever Middleware Test Company 2           1
Mappedin                                  1
GPTZero                                   1
White Bay                                 1
TEHORA inc.                               1
Sync.com                                  1
Navigator - Powered By LifeRaft           1
Coalition, Inc.                           1
Collective                                1
Abnormal Security                         1
GiftCash                                  1
Assent                                    1
eStaffing Inc.                            1
Binary Stream Software - ERP Solutions    1
Reddit, Inc.                              1
Everbridge                                1
Pivotree                                  1
Name: count, dtype: int64

In [25]:
print(sliced_df2.sector.value_counts())

sector
Software Development                                                                             9
IT Services and IT Consulting                                                                    7
Financial Services                                                                               7
Technology, Information and Internet                                                             6
Internet Publishing                                                                              3
Computer and Network Security                                                                    3
Software Development, Technology, Information and Internet, and Financial Services               2
Advertising Services, Software Development, and Technology, Information and Internet             2
Software Development and Technology, Information and Internet                                    2
Leasing Non-residential Real Estate                                                              1
IT Services and IT Consulting and Computer and Network Security                                  1
Consumer Services                                                                                1
IT Services and IT Consulting, Software Development, and Technology, Information and Internet    1
Insurance                                                                                        1
Technology, Information and Media                                                                1
Software Development, Computer Games, and IT System Custom Software Development                  1
Staffing and Recruiting                                                                          1
Software Development and Financial Services                                                      1
IT Services and IT Consulting and Software Development                                           1
Name: count, dtype: int64

In [27]:
print(sliced_df2.contractType.value_counts())

contractType
Full-time    51
Name: count, dtype: int64

In [33]:
print(dfLinkedinCanada.salary.value_counts())

salary
CA$140,000.00-CA$180,000.00    3
CA$70,000.00-CA$120,000.00     1
CA$110,000.00-CA$140,000.00    1
CA$250,000.00-CA$275,000.00    1
CA$80,000.00-CA$100,000.00     1
CA$80,000.00-CA$150,000.00     1
CA$120,000.00-CA$160,000.00    1
CA$100,000.00-CA$165,000.00    1
CA$85,000.00-CA$175,000.00     1
CA$80,000.00-CA$90,000.00      1
CA$70,000.00-CA$90,000.00      1
Name: count, dtype: int64

In [51]:
for indice in range(len(dfLinkedinCanada.salary)):
    if type(dfLinkedinCanada.salary[indice]) is not str: 
        dfLinkedinCanada.drop(indice, inplace=True)

KeyError: 0

In [49]:
dfLinkedinCanada

,applicationsCount,companyId,companyName,contractType,description,experienceLevel,location,postedTime,publishedAt,salary,sector,title,workType
32,Over 200 applicants,22291839.0,Webisoft,Full-time,"Webisoft is looking for an experienced, self-d...",Mid-Senior level,Canada,1 month ago,2023-11-27,"CA$70,000.00-CA$120,000.00",IT Services and IT Consulting,React Native Developer,Engineering and Information Technology
70,Over 200 applicants,86694680.0,Ascendion,Full-time,About Ascendion:\n\nAscendion is a full-servic...,Mid-Senior level,Canada,1 week ago,2024-01-10,"CA$110,000.00-CA$140,000.00",IT Services and IT Consulting and Computer Games,Back End Developer,Information Technology
134,Over 200 applicants,91442950.0,Teal.dev,NaN,Teal is a startup that allows SMB neobanks and...,Full-time,Canada,1 month ago,2023-12-18,"CA$250,000.00-CA$275,000.00",NaN,Platform Engineer,NaN
137,Over 200 applicants,77047100.0,GC Brokers,Full-time,Are you passionate about building innovative a...,Associate,Canada,1 week ago,2024-01-13,"CA$80,000.00-CA$100,000.00","Information Services and Technology, Informati...",Intermediate Software Engineer,Information Technology and Research
153,33 applicants,12901905.0,White Bay,Full-time,The Company:\n\n.\n\nA pioneering and forward-...,Mid-Senior level,"Vancouver, British Columbia, Canada",2 weeks ago,2024-01-03,"CA$140,000.00-CA$180,000.00","Software Development, Computer Games, and IT S...",Senior Gameplay Engineer | AAA Game | 100% Rem...,Art/Creative and Information Technology
191,Over 200 applicants,10865494.0,Super.com,Full-time,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",1 month ago,2023-12-05,"CA$80,000.00-CA$150,000.00","Transportation, Logistics, Supply Chain and St...",Intermediate Software Engineer (Remote),Engineering and Information Technology
201,Over 200 applicants,28649916.0,Solid State AI,Full-time,Solid State AI is on a mission to infuse creat...,Not Applicable,Canada,1 month ago,2023-12-12,"CA$120,000.00-CA$160,000.00",Semiconductors,Senior ML Engineer,Engineering and Information Technology
220,45 applicants,19138730.0,MedMe Health (YC W21),Full-time,"Hi, I’m Purya, Co-Founder & CEO at MedMe Healt...",Mid-Senior level,Canada,3 months ago,2023-10-20,"CA$140,000.00-CA$180,000.00",Software Development,Principal Engineer,Engineering and Information Technology
228,69 applicants,15197446.0,Humi,Full-time,In anticipation of future hiring needs in Earl...,Not Applicable,Canada,1 month ago,2023-11-30,"CA$140,000.00-CA$180,000.00",Human Resources Services,Expression of Interest - Senior Software Engin...,Engineering and Information Technology
230,64 applicants,10865494.0,Super.com,Internship,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",3 months ago,2023-10-16,"CA$100,000.00-CA$165,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Engineer - Internal Tools (Rem...,Engineering and Information Technology
262,Over 200 applicants,74040923.0,First Derivative,Full-time,KBD Developer\n\n\n\n\nFirst Derivative is a g...,Not Applicable,"Toronto, Ontario, Canada",2 weeks ago,2024-01-05,"CA$85,000.00-CA$175,000.00","Capital Markets, Software Development, and Fin...",KDB Developer,"Engineering, Information Technology, and Consu..."
263,163 applicants,976863.0,Eventbase,Full-time,We are looking for a Senior Software Developme...,Not Applicable,"Vancouver, British Columbia, Canada",1 month ago,2023-12-14,"CA$80,000.00-CA$90,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Development Engineer in Test (...,Engineering and Information Technology
268,Over 200 applicants,9207260.0,Riyo Games,Full-time,REMOTE ROLE!!\n\n\n\n\nRiyo Games was created ...,Associate,"Ontario, Canada",2 weeks ago,2024-01-04,"CA$70,000.00-CA$90,000.00",Computer Games,Intermediate Game Programmer,Information Technology

In [53]:
dfLinkedinCanada.drop(32, inplace=True)
dfLinkedinCanada

,applicationsCount,companyId,companyName,contractType,description,experienceLevel,location,postedTime,publishedAt,salary,sector,title,workType
70,Over 200 applicants,86694680.0,Ascendion,Full-time,About Ascendion:\n\nAscendion is a full-servic...,Mid-Senior level,Canada,1 week ago,2024-01-10,"CA$110,000.00-CA$140,000.00",IT Services and IT Consulting and Computer Games,Back End Developer,Information Technology
134,Over 200 applicants,91442950.0,Teal.dev,NaN,Teal is a startup that allows SMB neobanks and...,Full-time,Canada,1 month ago,2023-12-18,"CA$250,000.00-CA$275,000.00",NaN,Platform Engineer,NaN
137,Over 200 applicants,77047100.0,GC Brokers,Full-time,Are you passionate about building innovative a...,Associate,Canada,1 week ago,2024-01-13,"CA$80,000.00-CA$100,000.00","Information Services and Technology, Informati...",Intermediate Software Engineer,Information Technology and Research
153,33 applicants,12901905.0,White Bay,Full-time,The Company:\n\n.\n\nA pioneering and forward-...,Mid-Senior level,"Vancouver, British Columbia, Canada",2 weeks ago,2024-01-03,"CA$140,000.00-CA$180,000.00","Software Development, Computer Games, and IT S...",Senior Gameplay Engineer | AAA Game | 100% Rem...,Art/Creative and Information Technology
191,Over 200 applicants,10865494.0,Super.com,Full-time,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",1 month ago,2023-12-05,"CA$80,000.00-CA$150,000.00","Transportation, Logistics, Supply Chain and St...",Intermediate Software Engineer (Remote),Engineering and Information Technology
201,Over 200 applicants,28649916.0,Solid State AI,Full-time,Solid State AI is on a mission to infuse creat...,Not Applicable,Canada,1 month ago,2023-12-12,"CA$120,000.00-CA$160,000.00",Semiconductors,Senior ML Engineer,Engineering and Information Technology
220,45 applicants,19138730.0,MedMe Health (YC W21),Full-time,"Hi, I’m Purya, Co-Founder & CEO at MedMe Healt...",Mid-Senior level,Canada,3 months ago,2023-10-20,"CA$140,000.00-CA$180,000.00",Software Development,Principal Engineer,Engineering and Information Technology
228,69 applicants,15197446.0,Humi,Full-time,In anticipation of future hiring needs in Earl...,Not Applicable,Canada,1 month ago,2023-11-30,"CA$140,000.00-CA$180,000.00",Human Resources Services,Expression of Interest - Senior Software Engin...,Engineering and Information Technology
230,64 applicants,10865494.0,Super.com,Internship,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",3 months ago,2023-10-16,"CA$100,000.00-CA$165,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Engineer - Internal Tools (Rem...,Engineering and Information Technology
262,Over 200 applicants,74040923.0,First Derivative,Full-time,KBD Developer\n\n\n\n\nFirst Derivative is a g...,Not Applicable,"Toronto, Ontario, Canada",2 weeks ago,2024-01-05,"CA$85,000.00-CA$175,000.00","Capital Markets, Software Development, and Fin...",KDB Developer,"Engineering, Information Technology, and Consu..."
263,163 applicants,976863.0,Eventbase,Full-time,We are looking for a Senior Software Developme...,Not Applicable,"Vancouver, British Columbia, Canada",1 month ago,2023-12-14,"CA$80,000.00-CA$90,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Development Engineer in Test (...,Engineering and Information Technology
268,Over 200 applicants,9207260.0,Riyo Games,Full-time,REMOTE ROLE!!\n\n\n\n\nRiyo Games was created ...,Associate,"Ontario, Canada",2 weeks ago,2024-01-04,"CA$70,000.00-CA$90,000.00",Computer Games,Intermediate Game Programmer,Information Technology

In [55]:
low_salary = []
high_salary = []
average_salary = []
for salary in dfLinkedinCanada.salary:
    split_salary = salary.split('-')
    replaced_salary1 = float(split_salary[0].replace('CA$','').replace(",",""))
    replaced_salary2 = float(split_salary[1].replace('CA$','').replace(",",""))
    average = (replaced_salary1 + replaced_salary2) / 2
    low_salary.append(replaced_salary1)
    high_salary.append(replaced_salary2)
    average_salary.append(average)

In [57]:
dfLinkedinCanada['LOW_SALARY'] = low_salary
dfLinkedinCanada['HIGH_SALARY'] = high_salary
dfLinkedinCanada['AVERAGE_SALARY'] = average_salary

In [59]:
dfLinkedinCanada

,applicationsCount,companyId,companyName,contractType,description,experienceLevel,location,postedTime,publishedAt,salary,sector,title,workType,LOW_SALARY,HIGH_SALARY,AVERAGE_SALARY
70,Over 200 applicants,86694680.0,Ascendion,Full-time,About Ascendion:\n\nAscendion is a full-servic...,Mid-Senior level,Canada,1 week ago,2024-01-10,"CA$110,000.00-CA$140,000.00",IT Services and IT Consulting and Computer Games,Back End Developer,Information Technology,110000.0,140000.0,125000.0
134,Over 200 applicants,91442950.0,Teal.dev,NaN,Teal is a startup that allows SMB neobanks and...,Full-time,Canada,1 month ago,2023-12-18,"CA$250,000.00-CA$275,000.00",NaN,Platform Engineer,NaN,250000.0,275000.0,262500.0
137,Over 200 applicants,77047100.0,GC Brokers,Full-time,Are you passionate about building innovative a...,Associate,Canada,1 week ago,2024-01-13,"CA$80,000.00-CA$100,000.00","Information Services and Technology, Informati...",Intermediate Software Engineer,Information Technology and Research,80000.0,100000.0,90000.0
153,33 applicants,12901905.0,White Bay,Full-time,The Company:\n\n.\n\nA pioneering and forward-...,Mid-Senior level,"Vancouver, British Columbia, Canada",2 weeks ago,2024-01-03,"CA$140,000.00-CA$180,000.00","Software Development, Computer Games, and IT S...",Senior Gameplay Engineer | AAA Game | 100% Rem...,Art/Creative and Information Technology,140000.0,180000.0,160000.0
191,Over 200 applicants,10865494.0,Super.com,Full-time,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",1 month ago,2023-12-05,"CA$80,000.00-CA$150,000.00","Transportation, Logistics, Supply Chain and St...",Intermediate Software Engineer (Remote),Engineering and Information Technology,80000.0,150000.0,115000.0
201,Over 200 applicants,28649916.0,Solid State AI,Full-time,Solid State AI is on a mission to infuse creat...,Not Applicable,Canada,1 month ago,2023-12-12,"CA$120,000.00-CA$160,000.00",Semiconductors,Senior ML Engineer,Engineering and Information Technology,120000.0,160000.0,140000.0
220,45 applicants,19138730.0,MedMe Health (YC W21),Full-time,"Hi, I’m Purya, Co-Founder & CEO at MedMe Healt...",Mid-Senior level,Canada,3 months ago,2023-10-20,"CA$140,000.00-CA$180,000.00",Software Development,Principal Engineer,Engineering and Information Technology,140000.0,180000.0,160000.0
228,69 applicants,15197446.0,Humi,Full-time,In anticipation of future hiring needs in Earl...,Not Applicable,Canada,1 month ago,2023-11-30,"CA$140,000.00-CA$180,000.00",Human Resources Services,Expression of Interest - Senior Software Engin...,Engineering and Information Technology,140000.0,180000.0,160000.0
230,64 applicants,10865494.0,Super.com,Internship,About Super.com\n\nWe started Super.com to hel...,Not Applicable,"Toronto, Ontario, Canada",3 months ago,2023-10-16,"CA$100,000.00-CA$165,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Engineer - Internal Tools (Rem...,Engineering and Information Technology,100000.0,165000.0,132500.0
262,Over 200 applicants,74040923.0,First Derivative,Full-time,KBD Developer\n\n\n\n\nFirst Derivative is a g...,Not Applicable,"Toronto, Ontario, Canada",2 weeks ago,2024-01-05,"CA$85,000.00-CA$175,000.00","Capital Markets, Software Development, and Fin...",KDB Developer,"Engineering, Information Technology, and Consu...",85000.0,175000.0,130000.0
263,163 applicants,976863.0,Eventbase,Full-time,We are looking for a Senior Software Developme...,Not Applicable,"Vancouver, British Columbia, Canada",1 month ago,2023-12-14,"CA$80,000.00-CA$90,000.00","Transportation, Logistics, Supply Chain and St...",Senior Software Development Engineer in Test (...,Engineering and Information Technology,80000.0,90000.0,85000.0
268,Over 200 applicants,9207260.0,Riyo Games,Full-time,REMOTE ROLE!!\n\n\n\n\nRiyo Games was created ...,Associate,"Ontario, Canada",2 weeks ago,2024-01-04,"CA$70,000.00-CA$90,000.00",Computer Games,Intermediate Game Programmer,Information Technology,70000.0,90000.0,80000.0